### ISSUE TITLE
Request and Feature: Can you share .csv & .xlxs

### ISSUE THREAD

**Issue by MiChaelinzo** [jamsoft/uap-data-vis-tool#3]
Awesome tool you made! Can you also share the .csv & .xlxs data you collected for the UAP?

**Comment by jamsoft** [comment]
Thank you.

Not sure what did you're referring too? Do you mean the sightings data itself?

**Comment by MiChaelinzo** [comment]
> Thank you.
> 
> Not sure what did you're referring too? Do you mean the sightings data itself?

Yeah this one the raw data view https://github.com/jamsoft/uap-data-vis-tool/blob/main/img/raw-data.png

**Comment by jamsoft** [comment]
Oh those are detailed in the readme if you have a look at the top section it details where those files are online for download.

**Comment by jamsoft** [comment]
In this section ...

https://github.com/jamsoft/uap-data-vis-tool#initially-loading-data

**Comment by MiChaelinzo** [comment]
I didn't read and saw it, thank you for helping me out! Props to you!
